# Generated by Django 4.2.29 on 2026-07-07 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_analysis', '0002_initial'),
        ('requirement_analysis', '0003_add_model_relations'),
        ('requirement_analysis', '0003_knowledgegraphversion'),
    ]

    operations = [
    ]
