# Generated by Django 4.2.29 on 2026-04-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_factory', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugAnalysisRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version_tag', models.CharField(blank=True, default='', help_text='如 v6.0.0-release、2026-Q2-sprint5 等', max_length=100, verbose_name='版本标签')),
                ('source_type', models.CharField(choices=[('excel', 'Excel上传'), ('json_api', 'JSON API'), ('yunxiao_api', '云效API'), ('tapd_api', 'TAPD API')], default='excel', max_length=20, verbose_name='数据来源')),
                ('file_name', models.CharField(blank=True, default='', max_length=255, verbose_name='源文件名')),
                ('total_bugs', models.IntegerField(default=0, verbose_name='Bug总数')),
                ('raw_bugs', models.JSONField(default=list, verbose_name='原始Bug数据')),
                ('analysis_result', models.JSONField(default=dict, verbose_name='分析结果')),
                ('created_by', models.CharField(default='system', max_length=50, verbose_name='创建者')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'Bug分析记录',
                'verbose_name_plural': 'Bug分析记录',
                'db_table': 'df_bug_analysis_record',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='df_bug_anal_created_faaaf2_idx'), models.Index(fields=['source_type'], name='df_bug_anal_source__ebc4ba_idx'), models.Index(fields=['version_tag'], name='df_bug_anal_version_414268_idx'), models.Index(fields=['total_bugs'], name='df_bug_anal_total_b_f23cfe_idx')],
            },
        ),
    ]
