# Generated by Django 4.2.29 on 2026-07-07 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_factory', '0003_buganalysisrecord'),
        ('data_factory', '0007_buganalysisrecord_ai_progress_and_more'),
    ]

    operations = [
    ]
