# Generated by Django 4.2.29 on 2026-05-13 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='merged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='合入时间'),
        ),
    ]
