# Generated by Django 4.2.29 on 2026-05-13 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testcases', '0003_add_merged_at_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='merged_at',
        ),
        migrations.AddField(
            model_name='testcase',
            name='review_comment',
            field=models.TextField(blank=True, help_text='审核人员的意见', verbose_name='审核意见'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='review_status',
            field=models.CharField(choices=[('none', '未审核'), ('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='none', help_text='用例的审核状态：none-未审核, pending-待审核, approved-已通过, rejected-已拒绝', max_length=20, verbose_name='审核结果'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_testcases', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
    ]
