# Generated by Django 4.2.29 on 2026-05-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0004_remove_testcase_merged_at_testcase_review_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='review_status',
            field=models.CharField(choices=[('none', '未审核'), ('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', help_text='用例的审核状态：none-未审核, pending-待审核, approved-已通过, rejected-已拒绝', max_length=20, verbose_name='审核结果'),
        ),
    ]
