# Generated by Django 4.2.29 on 2026-07-06 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0005_update_review_status_default'),
        ('testcases', '0006_alter_testcase_project'),
    ]

    operations = [
    ]
