# Generated by Django 4.2.29 on 2026-07-07 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0007_testcase_review_comment_testcase_review_status_and_more'),
        ('testcases', '0008_merge_20260706_1122'),
    ]

    operations = [
    ]
