# Generated by Django 4.2.29 on 2026-05-13 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_testing', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=200, verbose_name='场景名称')),
                ('description', models.TextField(blank=True, verbose_name='场景描述')),
                ('global_variables', models.JSONField(default=dict, verbose_name='场景全局变量')),
                ('pre_script', models.TextField(blank=True, verbose_name='场景前置脚本')),
                ('post_script', models.TextField(blank=True, verbose_name='场景后置脚本')),
                ('flow_control', models.JSONField(default=dict, verbose_name='流程控制配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '自动化场景',
                'verbose_name_plural': '自动化场景',
                'db_table': 'api_automation_scenarios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='testsuiterequest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='apicollection',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='apicollection',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='apicollection',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否已删除'),
        ),
        migrations.AddField(
            model_name='apiproject',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='apiproject',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否已删除'),
        ),
        migrations.AddField(
            model_name='apirequest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='apirequest',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否已删除'),
        ),
        migrations.AddField(
            model_name='apirequest',
            name='path_params',
            field=models.JSONField(default=list, verbose_name='路径参数'),
        ),
        migrations.AddField(
            model_name='apirequest',
            name='variable_extractors',
            field=models.JSONField(default=list, verbose_name='变量提取规则'),
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否已删除'),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否已删除'),
        ),
        migrations.AddField(
            model_name='testexecution',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='testexecution',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否已删除'),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否已删除'),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='post_process_script',
            field=models.TextField(blank=True, verbose_name='后置处理脚本'),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='pre_process_script',
            field=models.TextField(blank=True, verbose_name='前置处理脚本'),
        ),
        migrations.AddField(
            model_name='testsuiterequest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='testsuiterequest',
            name='extracted_variables',
            field=models.JSONField(default=dict, verbose_name='变量提取规则'),
        ),
        migrations.AddField(
            model_name='testsuiterequest',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否已删除'),
        ),
        migrations.AddField(
            model_name='testsuiterequest',
            name='override_body',
            field=models.JSONField(blank=True, default=dict, verbose_name='覆盖请求体'),
        ),
        migrations.AddField(
            model_name='testsuiterequest',
            name='override_headers',
            field=models.JSONField(blank=True, default=dict, verbose_name='覆盖请求头'),
        ),
        migrations.AddField(
            model_name='testsuiterequest',
            name='override_method',
            field=models.CharField(blank=True, max_length=10, verbose_name='覆盖请求方法'),
        ),
        migrations.AddField(
            model_name='testsuiterequest',
            name='override_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='覆盖接口名称'),
        ),
        migrations.AddField(
            model_name='testsuiterequest',
            name='override_params',
            field=models.JSONField(blank=True, default=dict, verbose_name='覆盖请求参数'),
        ),
        migrations.AddField(
            model_name='testsuiterequest',
            name='override_url',
            field=models.TextField(blank=True, verbose_name='覆盖请求URL'),
        ),
        migrations.AddField(
            model_name='testsuiterequest',
            name='parent_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='父分组ID'),
        ),
        migrations.AddField(
            model_name='testsuiterequest',
            name='post_script',
            field=models.TextField(blank=True, verbose_name='后置脚本'),
        ),
        migrations.AddField(
            model_name='testsuiterequest',
            name='pre_script',
            field=models.TextField(blank=True, verbose_name='前置脚本'),
        ),
        migrations.AddField(
            model_name='testsuiterequest',
            name='step_type',
            field=models.CharField(default='request', max_length=20, verbose_name='步骤类型'),
        ),
        migrations.AlterField(
            model_name='testsuiterequest',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_testing.apirequest', verbose_name='API请求'),
        ),
        migrations.CreateModel(
            name='ScenarioExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('failed', '执行失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='执行状态')),
                ('execution_context', models.JSONField(default=dict, help_text='存储所有步骤的完整请求响应数据，用于跨步骤引用', verbose_name='执行上下文')),
                ('step_results', models.JSONField(default=list, verbose_name='步骤结果')),
                ('total_steps', models.IntegerField(default=0, verbose_name='总步骤数')),
                ('passed_steps', models.IntegerField(default=0, verbose_name='通过步骤数')),
                ('failed_steps', models.IntegerField(default=0, verbose_name='失败步骤数')),
                ('parent_step_number', models.IntegerField(blank=True, null=True, verbose_name='父场景步骤编号')),
                ('inherited_variables', models.JSONField(blank=True, default=dict, verbose_name='继承的变量')),
                ('exported_variables', models.JSONField(blank=True, default=dict, verbose_name='导出的变量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('executed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='执行者')),
                ('parent_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_executions', to='api_testing.scenarioexecution', verbose_name='父执行记录')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='api_testing.automationscenario', verbose_name='所属场景')),
            ],
            options={
                'verbose_name': '场景执行记录',
                'verbose_name_plural': '场景执行记录',
                'db_table': 'api_scenario_executions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='automationscenario',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='api_testing.apicollection', verbose_name='所属集合'),
        ),
        migrations.AddField(
            model_name='automationscenario',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_scenarios', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='automationscenario',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_testing.environment', verbose_name='执行环境'),
        ),
        migrations.AddField(
            model_name='automationscenario',
            name='legacy_test_suite',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenario', to='api_testing.testsuite', verbose_name='关联旧版测试套件'),
        ),
        migrations.AddField(
            model_name='automationscenario',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='api_testing.apiproject', verbose_name='所属项目'),
        ),
        migrations.CreateModel(
            name='TestSuiteReviewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('status', models.CharField(choices=[('pending', '待评审'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='评审状态')),
                ('comment', models.TextField(blank=True, verbose_name='评审意见')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='评审时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suite_review_records', to=settings.AUTH_USER_MODEL, verbose_name='评审人')),
                ('test_suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_records', to='api_testing.testsuite', verbose_name='测试套件')),
            ],
            options={
                'verbose_name': '测试套件评审记录',
                'verbose_name_plural': '测试套件评审记录',
                'db_table': 'api_test_suite_review_records',
                'ordering': ['-created_at'],
                'unique_together': {('test_suite', 'reviewer')},
            },
        ),
        migrations.CreateModel(
            name='ScenarioStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('step_type', models.CharField(choices=[('request', '接口请求'), ('group', '分组'), ('condition', '条件分支'), ('loop', '循环'), ('wait', '等待'), ('script', '自定义脚本'), ('scenario_ref', '引用场景')], default='request', max_length=20, verbose_name='步骤类型')),
                ('step_number', models.IntegerField(verbose_name='步骤编号')),
                ('step_alias', models.CharField(blank=True, max_length=100, verbose_name='步骤别名')),
                ('name', models.CharField(max_length=200, verbose_name='步骤名称')),
                ('scenario_ref_config', models.JSONField(blank=True, default=dict, help_text='{"inherit_variables": true, "pass_variables": ["var1", "var2"], "execution_mode": "sync"}', verbose_name='场景引用配置')),
                ('override_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('override_name', models.CharField(blank=True, max_length=200, verbose_name='覆盖名称')),
                ('override_method', models.CharField(blank=True, max_length=10, verbose_name='覆盖方法')),
                ('override_url', models.TextField(blank=True, verbose_name='覆盖URL')),
                ('override_headers', models.JSONField(blank=True, default=dict, verbose_name='覆盖请求头')),
                ('override_body', models.JSONField(blank=True, default=dict, verbose_name='覆盖请求体')),
                ('override_params', models.JSONField(blank=True, default=dict, verbose_name='覆盖参数')),
                ('override_assertions', models.JSONField(blank=True, default=list, verbose_name='覆盖断言规则')),
                ('override_extractors', models.JSONField(blank=True, default=list, verbose_name='覆盖变量提取规则')),
                ('pre_script', models.TextField(blank=True, verbose_name='步骤前置脚本')),
                ('post_script', models.TextField(blank=True, verbose_name='步骤后置脚本')),
                ('control_config', models.JSONField(blank=True, default=dict, help_text='条件、循环等配置，如 {"condition": "...", "loop_type": "for_each"}', verbose_name='控制配置')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('api_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_testing.apirequest', verbose_name='关联接口')),
                ('legacy_suite_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenario_step', to='api_testing.testsuiterequest', verbose_name='关联旧版套件请求')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api_testing.scenariostep', verbose_name='父步骤')),
                ('referenced_scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referenced_by_steps', to='api_testing.automationscenario', verbose_name='引用的场景')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api_testing.automationscenario', verbose_name='所属场景')),
            ],
            options={
                'verbose_name': '场景步骤',
                'verbose_name_plural': '场景步骤',
                'db_table': 'api_scenario_steps',
                'ordering': ['order', 'step_number'],
                'unique_together': {('scenario', 'step_number')},
            },
        ),
    ]
