# Generated by Django 4.2.29 on 2026-04-23 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainlineEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='环境名称')),
                ('description', models.TextField(blank=True, verbose_name='环境描述')),
                ('base_url', models.URLField(verbose_name='基础URL')),
                ('username', models.CharField(max_length=200, verbose_name='用户名')),
                ('password', models.CharField(max_length=500, verbose_name='密码')),
                ('additional_info', models.JSONField(blank=True, help_text='如Cookie、Token等', null=True, verbose_name='附加信息')),
                ('browser_type', models.CharField(default='chrome', max_length=50, verbose_name='浏览器类型')),
                ('headless', models.BooleanField(default=False, verbose_name='无头模式')),
                ('viewport', models.JSONField(blank=True, help_text='{"width": 1920, "height": 1080}', null=True, verbose_name='窗口大小')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mainline_environments', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '主线测试环境',
                'verbose_name_plural': '主线测试环境',
                'db_table': 'mainline_environments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MainlineTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='用例名称')),
                ('description', models.TextField(blank=True, verbose_name='用例描述')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('ready', '待生成'), ('generating', '生成中'), ('generated', '已生成'), ('running', '执行中'), ('passed', '通过'), ('failed', '失败')], default='draft', max_length=20, verbose_name='状态')),
                ('generated_script', models.TextField(blank=True, verbose_name='生成的测试脚本')),
                ('script_language', models.CharField(default='python', max_length=20, verbose_name='脚本语言')),
                ('script_framework', models.CharField(default='playwright', max_length=20, verbose_name='测试框架')),
                ('total_runs', models.IntegerField(default=0, verbose_name='执行次数')),
                ('passed_runs', models.IntegerField(default=0, verbose_name='通过次数')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='最后执行时间')),
                ('last_run_result', models.CharField(blank=True, max_length=20, verbose_name='最后执行结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainline_test_cases', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_cases', to='mainline.mainlineenvironment', verbose_name='测试环境')),
            ],
            options={
                'verbose_name': '主线测试用例',
                'verbose_name_plural': '主线测试用例',
                'db_table': 'mainline_test_cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MainlineTestStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.IntegerField(verbose_name='步骤序号')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('description', models.CharField(max_length=500, verbose_name='步骤描述（自然语言）')),
                ('action_type', models.CharField(blank=True, choices=[('navigate', '导航'), ('click', '点击'), ('fill', '输入'), ('select', '选择'), ('hover', '悬停'), ('wait', '等待'), ('screenshot', '截图'), ('assert_text', '断言文本'), ('assert_element', '断言元素存在'), ('assert_visible', '断言可见'), ('execute_script', '执行脚本'), ('switch_frame', '切换iframe'), ('switch_tab', '切换标签页'), ('scroll', '滚动')], max_length=50, verbose_name='操作类型')),
                ('target_selector', models.CharField(blank=True, max_length=500, verbose_name='目标选择器')),
                ('target_text', models.CharField(blank=True, max_length=500, verbose_name='目标文本')),
                ('action_params', models.JSONField(blank=True, null=True, verbose_name='操作参数')),
                ('expected_result', models.TextField(blank=True, verbose_name='预期结果')),
                ('expected_result_type', models.CharField(blank=True, max_length=50, verbose_name='预期结果类型')),
                ('expected_value', models.CharField(blank=True, max_length=500, verbose_name='预期值')),
                ('is_parsed', models.BooleanField(default=False, verbose_name='是否已解析')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='mainline.mainlinetestcase', verbose_name='所属用例')),
            ],
            options={
                'verbose_name': '主线测试步骤',
                'verbose_name_plural': '主线测试步骤',
                'db_table': 'mainline_test_steps',
                'ordering': ['step_order'],
            },
        ),
        migrations.CreateModel(
            name='MainlineTestExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', '待执行'), ('RUNNING', '执行中'), ('SUCCESS', '成功'), ('FAILED', '失败'), ('PARTIAL', '部分通过'), ('ABORTED', '中止')], default='PENDING', max_length=20, verbose_name='执行状态')),
                ('browser', models.CharField(default='chrome', max_length=50, verbose_name='浏览器')),
                ('headless', models.BooleanField(default=False, verbose_name='无头模式')),
                ('total_steps', models.IntegerField(default=0, verbose_name='总步骤数')),
                ('passed_steps', models.IntegerField(default=0, verbose_name='通过步骤数')),
                ('failed_steps', models.IntegerField(default=0, verbose_name='失败步骤数')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration', models.FloatField(default=0, verbose_name='执行时长(秒)')),
                ('result_data', models.JSONField(blank=True, null=True, verbose_name='执行结果详情')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('log_content', models.TextField(blank=True, verbose_name='执行日志')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('environment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='mainline.mainlineenvironment', verbose_name='执行环境')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mainline_executions', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='mainline.mainlinetestcase', verbose_name='测试用例')),
            ],
            options={
                'verbose_name': '主线测试执行记录',
                'verbose_name_plural': '主线测试执行记录',
                'db_table': 'mainline_test_executions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MainlineStepResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.IntegerField(default=0, verbose_name='步骤序号')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('passed', '通过'), ('failed', '失败'), ('skipped', '跳过')], default='pending', max_length=20, verbose_name='状态')),
                ('message', models.TextField(blank=True, verbose_name='结果消息')),
                ('actual_value', models.TextField(blank=True, verbose_name='实际结果值')),
                ('screenshot', models.TextField(blank=True, verbose_name='截图(base64)')),
                ('screenshot_path', models.CharField(blank=True, max_length=500, verbose_name='截图路径')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration', models.FloatField(default=0, verbose_name='执行时长(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_results', to='mainline.mainlinetestexecution', verbose_name='执行记录')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='mainline.mainlineteststep', verbose_name='测试步骤')),
            ],
            options={
                'verbose_name': '步骤执行结果',
                'verbose_name_plural': '步骤执行结果',
                'db_table': 'mainline_step_results',
                'ordering': ['step_order'],
            },
        ),
    ]
