# Generated by Django 4.2.29 on 2026-07-06 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0003_add_expected_result_to_test_case_step'),
        ('ui_automation', '0006_aiexecutionrecord_ai_test_suite'),
    ]

    operations = [
    ]
